CREATE TABLE mesas
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero INT         NOT NULL UNIQUE,
    status VARCHAR(30) NOT NULL,
    CONSTRAINT chk_mesas_status
        CHECK (status IN ('LIVRE', 'OCUPADA', 'AGUARDANDO_PAGAMENTO'))
);

CREATE TABLE usuarios
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR(100) NOT NULL UNIQUE,
    senha   VARCHAR(100) NOT NULL,
    perfil  VARCHAR(30)  NOT NULL,
    ativo   BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_usuarios_perfil
        CHECK (perfil IN ('ADM', 'GARCOM', 'COZINHA', 'CAIXA'))
);

CREATE TABLE produtos
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome  VARCHAR(150)   NOT NULL,
    preco NUMERIC(10, 2) NOT NULL,
    ativo BOOLEAN        NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_produtos_preco
        CHECK (preco >= 0)
);

CREATE TABLE pedidos
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mesa_id          BIGINT      NOT NULL,
    status_preparo   VARCHAR(30) NOT NULL,
    status_pagamento VARCHAR(30) NOT NULL,
    CONSTRAINT fk_pedidos_mesa
        FOREIGN KEY (mesa_id) REFERENCES mesas (id),
    CONSTRAINT chk_pedidos_status_preparo
        CHECK (status_preparo IN ('RECEBIDO', 'EM_PREPARO', 'PRONTO', 'ENTREGUE')),
    CONSTRAINT chk_pedidos_status_pagamento
        CHECK (status_pagamento IN ('ABERTO', 'FECHADO', 'PAGO'))
);

CREATE TABLE itens_pedido
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id      BIGINT         NOT NULL,
    produto_id     BIGINT         NOT NULL,
    quantidade     INT            NOT NULL,
    preco_unitario NUMERIC(10, 2) NOT NULL,
    CONSTRAINT fk_itens_pedido_pedido
        FOREIGN KEY (pedido_id) REFERENCES pedidos (id),
    CONSTRAINT fk_itens_pedido_produto
        FOREIGN KEY (produto_id) REFERENCES produtos (id),
    CONSTRAINT chk_itens_pedido_quantidade
        CHECK (quantidade > 0),
    CONSTRAINT chk_itens_pedido_preco_unitario
        CHECK (preco_unitario >= 0)
);